### ISSUE TITLE
ArgumentError: VCR::Response even when VCR is turned off

### ISSUE THREAD

**Issue by alexwebgr** [vcr/vcr#1008]
This is a situation which involves both VCR and webmock. wasn't sure which project it since i am getting errors from both gems.

i am trying to call an endpoint with Net::HTTP and pass some query params everything is working fine in the browser but when i try to test it, it blows up :( 
```
url = [Settings.api_host, API_VERSION, endpoint].join("/")
uri = URI(url)
query_params = { "status_spark_value_not_eq_any[]": InventoryStatus::SOLD_STATUSES }

uri.query = URI.encode_www_form(query_params)

req = Net::HTTP::Get.new(uri)

res = Net::HTTP.start(uri.hostname, uri.port) { |http|
  http.request(req) <------ line 33
}
```
i have created a stub_request for the API call that looks like this

```
RSpec.shared_context("request_forms") do
  def list_inventories_valid_stub
    url = [Settings.api_host, Requests::CallApiEndpoint::API_VERSION, "requests/inventory"].join("/")
    query_params = { "status_not_eq_any[]": InventoryStatus::SOLD_STATUSES }

    WebMock.stub_request(:get, url)
      .with(
        query: query_params
      )
      .to_return(status: 200, body: [])
  end
end
```
then i include it in the spec
```
    include_context "request_forms"

    before { list_inventories_valid_stub }
```

when i run the test i get this error
```
WebMock::NetConnectNotAllowedError:
Real HTTP connections are disabled. Unregistered request: GET http://test-

You can stub this request with the following snippet:

stub_request(:get, "http://test-api.domain.re/v2/requests/inventory?status_not_eq_any%5B%5D=completed&status_not_eq_any%5B%5D=firm")
registered request stubs:

stub_request(:get, "http://test-api.domain.re/v2/requests/inventory?status_not_eq_any%5B%5D%5B%5D=completed&status_not_eq_any%5B%5D%5B%5D=firm")

============================================================
# ./app/services/requests/call_api_endpoint.rb:33:in `block in call'

```

the only difference is that the params for `status_not_eq_any` have two sets of square brackets

when i hard-code the url in the stub exactly like in the suggestion i get this error 
```

     ArgumentError:
       VCR::Response initialized with an invalid (non-String) body of class Array: [].
     # ./app/services/requests/call_api_endpoint.rb:33:in `block in call'
```

InventoryStatus::SOLD_STATUSES is an array but even when i join them into a string i still get the same error as above
 
### VCR configuration
```
require "vcr"
require "webmock"

WebMock.enable!

VCR.configure do |c|
  c.cassette_library_dir = "spec/fixtures/cassettes"
  c.hook_into :webmock

  c.default_cassette_options = {
    record: :new_episodes,
    preserve_exact_body_bytes: true
  }

  c.configure_rspec_metadata!
end
```

i have added the snippet to turn off VCR for requests that have the VCR tag
```
  config.around do |example|
    if example.metadata.key?(:vcr)
      example.run
    else
      VCR.turned_off { example.run }
    end
  end
```

Ruby 3.1.2
Gem 3.3.7
WebMock 3.8.3
Rails 6.1.7.6
Rspec rspec-rails (5.0.2)

my questions are
why is webmock parsing the params in such a way?
why is VCR throwing an error even when in theory it is turned off?
how can i turn it off completely for that test?

**Comment by alexwebgr** [comment]
i think the VCR happens because the it expects the response to be a string too :)

**Comment by alexwebgr** [comment]
and for the double brackets, array notation, i just removed it from the params
