### ISSUE TITLE
Regression in VCR 6.3.0: `cannot load such file -- faraday/multipart`

### ISSUE THREAD

**Issue by myronmarston** [vcr/vcr#1031]
The faraday support in VCR 6.3.0 attempts to require `faraday/multipart`, but this gem won't necessarily be available on most projects--it's not included by default when a project uses faraday.  This leads to a `LoadError` on VCR 6.3.0 that does not happen on prior versions of VCR.

To reproduce, put this into `tmp/vcr_bug.rb`:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "vcr", ENV.fetch("VCR_VERSION")
  gem "faraday", "~> 2.10.1"
end

require "faraday"
require "tmpdir"
require "vcr"

VCR.configure do |vcr|
  vcr.hook_into :faraday
  vcr.cassette_library_dir = ::Dir.mktmpdir
end

VCR.use_cassette("example") do
  puts Faraday.get("https://httpstat.us/200").body
end
```

Then run it with `VCR_VERSION` set to an appropriate version to observe the regression:

```
$ VCR_VERSION=6.0.0 ruby tmp/vcr_bug.rb
/Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.0.0/lib/vcr/structs.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of vcr-6.0.0 to add base64 into its gemspec.
200 OK
$ VCR_VERSION=6.1.0 ruby tmp/vcr_bug.rb
/Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.1.0/lib/vcr/structs.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of vcr-6.1.0 to add base64 into its gemspec.
200 OK
$ VCR_VERSION=6.2.0 ruby tmp/vcr_bug.rb
/Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.2.0/lib/vcr/structs.rb:1: warning: base64 was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile or gemspec. Also contact author of vcr-6.2.0 to add base64 into its gemspec.
200 OK
$ VCR_VERSION=6.3.0 ruby tmp/vcr_bug.rb
/Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require': cannot load such file -- faraday/multipart (LoadError)
        from /Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/middleware/faraday.rb:2:in `<top (required)>'
        from /Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/library_hooks/faraday.rb:1:in `<top (required)>'
        from /Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/myron/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/configuration.rb:513:in `load_library_hook'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/configuration.rb:66:in `block in hook_into'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/configuration.rb:66:in `each'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr/configuration.rb:66:in `hook_into'
        from tmp/vcr_bug.rb:15:in `block in <main>'
        from /Users/myron/.rvm/gems/ruby-3.3.4/gems/vcr-6.3.0/lib/vcr.rb:235:in `configure'
        from tmp/vcr_bug.rb:14:in `<main>'
```

#### Versions

Ruby 3.3.4
Gem 6.3.0

**Comment by myronmarston** [comment]
It looks like this regressed in https://github.com/vcr/vcr/pull/1024/files#diff-1d24f0c89e794754bff0283cbc4ade03dfee6a3371df1cdb575c03ff25dcacc7, but it's not clear to me why the require was added there.

**Comment by olleolleolle** [comment]
The `require` was _probably_ put there due to the names of the `FilePart`/`UploadIO` classes changing, in a rename in the Faraday 2.0 major upgrade.

Perhaps that require should remain, and then raise an exception explaining that the optional Faraday 2.0 dependency requires the `faraday-multipart` gem for this usage. (Since it's an optional dependency on vcr, it's nuanced.)

**Comment by colinbruce** [comment]
The issue seems to be that [this line](https://github.com/vcr/vcr/pull/1024/files#diff-1d24f0c89e794754bff0283cbc4ade03dfee6a3371df1cdb575c03ff25dcacc7R2) adds the requirement to the library file to make the test pass linked above.  

Our code did not exercise the FilePart/UploadIO and all tests passed fine with VCR 6.2.0.

Now we would have to add the additional gem explicitly to our gemfile, this seems like an anti-pattern :/

**Comment by olleolleolle** [comment]
Making an attempt moving the require to the spec/ directory's file where it is being used. Seemed way simpler. Thanks, colinbruce for wording your comment like you did!
