### ISSUE TITLE
Adding multipart header causes VCR::Request error

### ISSUE THREAD

**Issue by jwoertink** [vcr/vcr#261]
I'm using Faraday, and in my test I'm doing a PUT to a controller in my app. My PUT is trying to upload a file (updating user avatar). When I add 

``` ruby
header 'Content-Type', 'multipart/form-data'
```

to my `RSpec.configure` block, I get the following error:

``` text
Failure/Error: And I PUT to "/users" with the query:
     ArgumentError:
       VCR::Request initialized with an invalid body: {"user"=>{"avatar"=>#<Rack::Test::UploadedFile:0x007f94e09a5c28 @content_type="image/jpeg", @original_filename="sample.jpg", @tempfile=#<File:/var/folders/3_/9h28vh2j3ml4nm4n3y3fzgsh0000gn/T/sample.jpg20130129-77524-1a5nz8u>>}}.
```

I have my uploaders set to `config.storage = :file` so VCR shouldn't even be making any calls at this point. If I remove that header, then I don't get a VCR error (although test still fails >_<)

Maybe I'm missing something?

**Comment by moneypenny** [comment]
Hm, I still get this error with VCR 2.9.3 with both `c.hook_into :typhoeus` and `c.hook_into :webmock` while trying to do a multipart file upload with `Faraday::UploadIO`.

**Comment by krainboltgreene** [comment]
Can you create a standalone reproduction?

**Comment by jiacai2050** [comment]
I also see this issue when use `Faraday::UploadIO`,  hook_into is configured to `:webmock, :typhoeus`
```rb
    def upload_file(uri, local_file_abs_path, content_type='Content-Type: text/plain;charset=UTF-8')
      payload = { 'file' => Faraday::UploadIO.new(local_file_abs_path, content_type) }
      @session.post do |req| 
        req.body = payload
        req.headers = generate_headers(uri, :post, content_type)
      end
    end
```

Error msg:
```
ArgumentError: VCR::Request initialized with an invalid body: {"file"=>#<UploadIO:0x007f09fc6cf630 @content_type="Content-Type: text/plain;charset=UTF-8", @original_filename="test_sensitive_word.txt", @local_path="/vagrant/ul
uru-platform/uluru-api/test/app-test/test/test_sensitive_word.txt", @io=#<File:/vagrant/uluru-platform/uluru-api/test/app-test/test/test_sensitive_word.txt>, @opts={}>}.
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/structs.rb:65:in `initialize'
     62:         super
     63:
     64:         if body && !body.is_a?(String)
  => 65:           raise ArgumentError, "#{self.class} initialized with an invalid body: #{body.inspect}."
     66:         end
     67:
     68:         # Ensure that the body is a raw string, in case the string instance
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/structs.rb:206:in `initialize'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/library_hooks/webmock.rb:46:in `new'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/library_hooks/webmock.rb:46:in `vcr_request_for'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/library_hooks/webmock.rb:119:in `vcr_request'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/request_handler.rb:107:in `request_summary'
/home/vagrant/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/vcr-4.0.0/lib/vcr/request_handler.rb:7:in `handle'
```
