### ISSUE TITLE
ruby 2.0 upgrade problem - key not found: "recorded_at" (KeyError) 

### ISSUE THREAD

**Issue by kbaum** [vcr/vcr#270]
When trying to upgrade to ruby 2.0.0 i get the following error when trying to record a new cassette.  I was at vcr 2.4.0 but i tried using edge to see if that would fix.

```
   key not found: "recorded_at" (KeyError)
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/structs.rb:496:in `fetch'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/structs.rb:496:in `from_hash'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:153:in `block in previously_recorded_interactions'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:153:in `map'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:153:in `previously_recorded_interactions'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:213:in `merged_interactions'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:226:in `interactions_to_record'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:108:in `serializable_hash'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:233:in `write_recorded_interactions_to_disk'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/cassette.rb:60:in `eject'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr.rb:140:in `eject_cassette'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/bundler/gems/vcr-71a1b2a9f161/lib/vcr/test_frameworks/cucumber.rb:56:in `block (2 levels) in tags'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/core_ext/instance_exec.rb:48:in `instance_exec'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/core_ext/instance_exec.rb:48:in `block in cucumber_instance_exec'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/core_ext/instance_exec.rb:69:in `cucumber_run_with_backtrace_filtering'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/core_ext/instance_exec.rb:36:in `cucumber_instance_exec'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/rb_support/rb_hook.rb:14:in `invoke'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:114:in `invoke'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:108:in `block in execute_after'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:107:in `reverse_each'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:107:in `execute_after'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:19:in `after'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:112:in `block in fire_hook'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:111:in `each'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:111:in `fire_hook'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime.rb:111:in `after'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime.rb:98:in `before_and_after'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime.rb:80:in `block in with_hooks'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:120:in `call'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:120:in `block (3 levels) in around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:9:in `block in around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:97:in `call'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:97:in `execute_around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/language_support/language_methods.rb:8:in `around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:119:in `block (2 levels) in around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:123:in `call'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime/support_code.rb:123:in `around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime.rb:92:in `around'
      /Users/karl/.rvm/gems/ruby-2.0.0-p0@viewthespace/gems/cucumber-1.2.2/lib/cucumber/runtime.rb:79:in `with_hooks'
```

**Comment by beechnut** [comment]
Thank you @radicaled. That follow-up helped me almost exactly two years after you posted it. :+1: :laughing:

**Comment by lashleigh** [comment]
And it helped me another 2 years after that one :) Now I really know I'm working on a legacy project...
