### ISSUE TITLE
Intermittent exceptions caused by "undefined method `resume'"

### ISSUE THREAD

**Issue by bilts** [vcr/vcr#376]
Running rspec tests using capybara against a Rails project produces intermittent exceptions coming from VCR's around_http_request implementation.  The error may appear on any tests and varies from run to run.

VCR Configuration in config/environments/test.rb

```
VCR.configure do |c|
  c.cassette_library_dir = 'fixtures/cassettes'
  c.hook_into :faraday
  c.around_http_request do |request|
    VCR.use_cassette('global', :record => :new_episodes, &request)
  end
end
```

Stack trace:

```
 Failure/Error: Unable to find matching line from backtrace
 NoMethodError:
   undefined method `resume' for nil:NilClass
 # /gem-root/gems/vcr-2.6.0/lib/vcr/configuration.rb:510:in `resume_fiber'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/configuration.rb:405:in `block in around_http_request'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/hooks.rb:14:in `conditionally_invoke'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/hooks.rb:29:in `block in invoke_hook'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/hooks.rb:28:in `map'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/util/hooks.rb:28:in `invoke_hook'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/request_handler.rb:51:in `invoke_after_request_hook'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/middleware/faraday.rb:108:in `invoke_after_request_hook'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/middleware/faraday.rb:48:in `ensure in handle'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/middleware/faraday.rb:48:in `handle'
 # /gem-root/gems/vcr-2.6.0/lib/vcr/middleware/faraday.rb:31:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday_middleware-0.9.0/lib/faraday_middleware/response_middleware.rb:30:in `call'
 # /gem-root/gems/faraday-0.8.8/lib/faraday/response.rb:8:in `call'
 # ./lib/echo/client_middleware/logging_middleware.rb:32:in `block in call'
 # ./lib/echo/util.rb:6:in `time'
 # ./lib/echo/client_middleware/logging_middleware.rb:32:in `call'
 # /gem-root/gems/faraday-0.8.8/lib/faraday/connection.rb:253:in `run_request'
 # /gem-root/gems/faraday-0.8.8/lib/faraday/connection.rb:106:in `get'
 # ./lib/echo/client.rb:38:in `get'
 # ./lib/echo/client.rb:28:in `get_facets'
 # ./app/controllers/datasets_controller.rb:27:in `facets'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 # /gem-root/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:189:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/rendering.rb:10:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:18:in `block in process_action'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:383:in `_run__3008474776278095672__process_action__callbacks'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
 # /gem-root/gems/actionpack-4.0.0/lib/abstract_controller/callbacks.rb:17:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/rescue.rb:29:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `block in instrument'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/notifications.rb:159:in `instrument'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
 # /gem-root/gems/activerecord-4.0.0/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 # /gem-root/gems/actionpack-4.0.0/lib/abstract_controller/base.rb:136:in `process'
 # /gem-root/gems/actionpack-4.0.0/lib/abstract_controller/rendering.rb:44:in `process'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal.rb:195:in `dispatch'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 # /gem-root/gems/actionpack-4.0.0/lib/action_controller/metal.rb:231:in `block in action'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:80:in `dispatch'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:48:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:71:in `block in call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `each'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/journey/router.rb:59:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/routing/route_set.rb:655:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/flash.rb:241:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
 # /gem-root/gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/cookies.rb:486:in `call'
 # /gem-root/gems/activerecord-4.0.0/lib/active_record/query_cache.rb:36:in `call'
 # /gem-root/gems/activerecord-4.0.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:626:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:373:in `_run__1584031291513316687__call__callbacks'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/callbacks.rb:80:in `run_callbacks'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 # /gem-root/gems/railties-4.0.0/lib/rails/rack/logger.rb:38:in `call_app'
 # /gem-root/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `block in call'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `block in tagged'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:25:in `tagged'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/tagged_logging.rb:67:in `tagged'
 # /gem-root/gems/railties-4.0.0/lib/rails/rack/logger.rb:21:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/request_id.rb:21:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
 # /gem-root/gems/activesupport-4.0.0/lib/active_support/cache/strategy/local_cache.rb:83:in `call'
 # /gem-root/gems/actionpack-4.0.0/lib/action_dispatch/middleware/static.rb:64:in `call'
 # /gem-root/gems/railties-4.0.0/lib/rails/engine.rb:511:in `call'
 # /gem-root/gems/railties-4.0.0/lib/rails/application.rb:97:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/builder.rb:138:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
 # /gem-root/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
 # /gem-root/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
 # /gem-root/gems/capybara-2.1.0/lib/capybara/server.rb:19:in `call'
 # /gem-root/gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
 # /ruby-root/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
 # /ruby-root/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
 # /ruby-root/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by fotinakis** [comment]
FWIW, I was able to fix this for myself by using a mutex and synchronizing all HTTP threads handled by VCR:

```Ruby
require 'thread'

global_vcr_semaphore = Mutex.new

VCR.configure do |c|
  c.around_http_request do |request|
    global_vcr_semaphore.synchronize do
      request.proceed
    end
  end
end
```

This of course forces all HTTP requests to happen serially in tests, but might be a useable workaround.

**Comment by mrbrdo** [comment]
With https://github.com/vcr/vcr/pull/512 you should at least see the actual error, if it doesn't also fix the issue.

**Comment by coding-bunny** [comment]
I've upgraded VCR to the 5.x version, but this problem is also cropping up in a specific branch.
And I'm not sure how to explain the cause.

I've basically replaced some models in the controllers to pull data over an API instead of the DB, meaning additional HTTP calls are being made on normal requests, and I feel this is related to the problem here. The tests pass just fine on production cause the cassettes cover everything.

But in the new branch, we switched to this approach, and now I have tests failing because of this.
The weird part is, it works locally fine if I use for example `rails test` to invoke the test-suite.
But when I use `bundle exec rake` or `bin/test` to invoke the suite, these errors pop-up. And it's caused by Capybara tests using Chromium, everything else actually just works.

So for some reason these nested calls only happen in these specific conditions for us.
