### ISSUE TITLE
Disable VCR in a scenario? VCR.turned_off seems doesn't work for me.

### ISSUE THREAD

**Issue by samnang** [vcr/vcr#407]
I tried to temporary disable VCR in a senario in my spec suit. But I can't get it to work. I have tried different options like `VCR.turned_off`, `VCR::Configuration#ignore_hosts`, and `VCR::Configuration#ignore_request`, but none of those work for me. When I tried to comment `vcr` in my `Gemfile`, it works just fine. I'm using `vcr-2.9.0` with `webmock-1.16.1`.

``` ruby
require 'spec_helper'

describe S3PhotoWorker do
  let(:remote_file_url) { "http://s3.amazon.com/files/photo.jpg" }

  it 'pulls image from s3 for processing' do
    VCR.turned_off do
      stub_request(:get, remote_file_url)
        .to_return(body: fixture_file('post_photo.jpg'),
                   headers: { 'Content-Type' => 'image/jpg' })

      post = create(:post, unprocessed_photo_url: remote_file_url)

      S3PhotoWorker.new.perform(post, remote_file_url)

      expect(post.reload.photo.url).not_to be_blank
    end
  end
end
```

Here is the error message:

```
Failures:

  1) S3PhotoWorker pulls image from s3 for processing
     Failure/Error: S3PhotoWorker.new.perform(post, remote_file_url)
     ActiveRecord::RecordInvalid:
       Validation failed: Photo could not download file: VCR::Response initialized with an invalid body: #<Rack::Test::UploadedFile:0x007fb03cdd4b60 @content_type="text/plain", @original_filename="post_photo.jpg", @tempfile=#<Tempfile:/var/folders/nv/csqxfl2d7xsfmsqwn2zpp72c0000gn/T/post_photo.jpg20140501-20008-17xypia>>.
     # ./app/workers/s3_photo_worker.rb:7:in `perform'
     # ./spec/workers/s3_photo_worker_spec.rb:16:in `block (3 levels) in <top (required)>'
     # ./spec/workers/s3_photo_worker_spec.rb:7:in `block (2 levels) in <top (required)>'
     # -e:1:in `<main>'

Finished in 0.4201 seconds
1 example, 1 failure

Failed examples:

rspec ./spec/workers/s3_photo_worker_spec.rb:6 # S3PhotoWorker pulls image from s3 for processing
```

**Comment by chrishough** [comment]
could this be related to https://github.com/vcr/vcr/issues/950 ?
