### ISSUE TITLE
Turning off VCR inside around_http_request seems to cause strange fibre errors

### ISSUE THREAD

**Issue by brightbits** [vcr/vcr#494]
We are turning off VCR based on the uri, like so:

```ruby
VCR.configure do |c|
  c.around_http_request(lambda {|r| r.uri =~ /<regexp>/}) do |request|
    VCR.turned_off(&request)
  end

  c.ignore_localhost = true
  c.cassette_library_dir = 'spec/support/fixtures/cassettes'
  c.hook_into :webmock
  c.configure_rspec_metadata!
  c.default_cassette_options = { record: :none }
end
```

Sometimes we get this error:
```
  undefined method `resume' for nil:NilClass
  
  /<gem path>/vcr-2.9.3/lib/vcr/configuration.rb:510:in `resume_fiber'
  /<gem path>/vcr-2.9.3/lib/vcr/configuration.rb:405:in `block in around_http_request'
  /<gem path>/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
  /<gem path>/vcr-2.9.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
  /<gem path>/vcr-2.9.3/lib/vcr/util/hooks.rb:14:in `conditionally_invoke'
  /<gem path>/vcr-2.9.3/lib/vcr/util/hooks.rb:29:in `block in invoke_hook'
  /<gem path>/vcr-2.9.3/lib/vcr/util/hooks.rb:28:in `map'
  /<gem path>/vcr-2.9.3/lib/vcr/util/hooks.rb:28:in `invoke_hook'
  /<gem path>/vcr-2.9.3/lib/vcr/library_hooks/webmock.rb:141:in `block in <module:WebMock>'
  /<gem path>/webmock-1.18.0/lib/webmock/callback_registry.rb:20:in `call'
  /<gem path>/webmock-1.18.0/lib/webmock/callback_registry.rb:20:in `block in invoke_callbacks'
  /<gem path>/webmock-1.18.0/lib/webmock/callback_registry.rb:15:in `each'
  /<gem path>/webmock-1.18.0/lib/webmock/callback_registry.rb:15:in `invoke_callbacks'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:89:in `block in request'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:98:in `call'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:98:in `block in request'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:105:in `call'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:105:in `block in request'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:137:in `start_with_connect_without_finish'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:104:in `request'
  /<gem path>/capybara-2.4.4/lib/capybara/server.rb:56:in `block in responsive?'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
  /<gem path>/webmock-1.18.0/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
  /<gem path>/capybara-2.4.4/lib/capybara/server.rb:56:in `responsive?'
  /<gem path>/capybara-2.4.4/lib/capybara/server.rb:73:in `block in boot'
  /<gem path>/capybara-2.4.4/lib/capybara/server.rb:73:in `boot'
  /<gem path>/capybara-2.4.4/lib/capybara/session.rb:66:in `initialize'
  /<gem path>/capybara-2.4.4/lib/capybara.rb:248:in `new'
  /<gem path>/capybara-2.4.4/lib/capybara.rb:248:in `current_session'
  /<gem path>/capybara-2.4.4/lib/capybara/dsl.rb:46:in `page'
  ./spec/spec_helper.rb:53:in `block (2 levels) in <top (required)>'
```

It appears that the fibre for the current thread doesn't exist after the request has been executed.. Any idea why this could be?

Thanks

**Comment by mrbrdo** [comment]
Try https://github.com/vcr/vcr/pull/512

**Comment by krainboltgreene** [comment]
Can you retry this @brightbits with 3.0.0?

**Comment by clupprich** [comment]
I think I've run into the same issue (same setup, same stacktrace as above).

I've bundled vcr from the latest master (573fff9a51ef1f1354d70de0e7253ff1d4bc91be). I've created a small gist with a simple script here: https://gist.github.com/clupprich/d9f9dece626508028ae9.

**Comment by mrbrdo** [comment]
could you also show us the error and backtrace? because the error may be a bit more descriptive since 3.0.0

**Comment by clupprich** [comment]
Sure!

```
/Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/configuration.rb:511:in `resume_fiber': undefined method `resume' for nil:NilClass (NoMethodError)
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/configuration.rb:405:in `block in around_http_request'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/util/hooks.rb:14:in `conditionally_invoke'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/util/hooks.rb:29:in `block in invoke_hook'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/util/hooks.rb:28:in `map'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/util/hooks.rb:28:in `invoke_hook'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bundler/gems/vcr-573fff9a51ef/lib/vcr/library_hooks/webmock.rb:141:in `block in <module:WebMock>'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/callback_registry.rb:20:in `block in invoke_callbacks'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/callback_registry.rb:15:in `each'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/callback_registry.rb:15:in `invoke_callbacks'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/net_http.rb:81:in `request'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:1308:in `request_get'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:481:in `block in get_response'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/webmock-1.22.6/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:584:in `start'
	from /Users/kitto/.rbenv/versions/2.3.0/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
	from test.rb:20:in `block (2 levels) in <main>'
```

**Comment by mrbrdo** [comment]
Huh. Just from feeling it seems like after_http_request is called before before_http_request, or something. Also I have to say `hook_allowed` in `around_http_request` is not thread-safe. Although I'm not sure this would definitely solve your issue, it's pretty likely (if `hook_allowed` was implemented similar to `fibers` and `fiber_errors`). I really don't have time to work on this right now, and also I wouldn't want to be the only guy who ever does anything threadsafety-related :) But I suggest you try this change and submit a PR if it works for you.

**Comment by clupprich** [comment]
Thanks for the hints, Jan! I'll fiddle around with things a bit tomorrow and see if I can come up with a PR.

**Comment by mrbrdo** [comment]
Also as an afterthought, I am still in support of https://github.com/vcr/vcr/issues/461 since this functionality is so often the source of bugs and also a big source of complexity. I know this doesn't help you, but just wanted to throw this out there again :)

**Comment by clupprich** [comment]
;) It will still be good practice for me and interesting to see some internal of VCR, so I'll give it a try anyways.

**Comment by mrbrdo** [comment]
:+1:

**Comment by clupprich** [comment]
I spent some time yesterday evening and this morning trying to understand what's happening and why it's happening. It seems to be a timing issue, like you said, @mrbrdo, because when I insert a `puts` into the `before_http_request` it doesn't seem to happen. I'd need to read a lot more code to understand what's going on, but for now I will just switch away from using `around_http_request`.

**Comment by sriedel** [comment]
I'm running into the exact situation right now as well. 
@clupprich: did you make any progress or find a workaround?

**Comment by clupprich** [comment]
I think I've stopped using `around_http_request` alltogether, and things worked fine.

**Comment by fabriziobertoglio1987** [comment]
I am experiencing the same issue and very new to VCR. I experience the issue inside the following class

```
class Storm
  include HTTParty
  ....
  def getTide
       self.class.get("/tide/extremes/point", @options)
  end
end
``` 

and my rails_helper is 

```
  c.around_http_request(lambda { |req| req.uri =~ /storm/ }) do |request|
    VCR.use_cassette(request.uri, &request)
  end
```
The class makes different types of requests to the same `api.stormglass` endpoint. This seems to be causing the issue. 
My solution is disable VCR for this request and `stub` them manually

```
  c.around_http_request(lambda {|r| r.uri =~ /storm/}) do |request|
    VCR.turned_off(&request)
  end
```
I disabled every VCR request and ended up mocking those request manually with webmock
and stub the http request inside the example 

```
```

**Comment by fabriziobertoglio1987** [comment]
I am experiencing this issue and I will remove VCR gem
