### ISSUE TITLE
VCR fails when response body is BOM|UTF16LE

### ISSUE THREAD

**Issue by ixti** [vcr/vcr#612]
When trying to record request that responds with gzipped BOM|UTF16LE body (`Content-Encoding` is correctly set to `gzip`), my sepc fails (and no cassette file created) with: 

```
          Encoding::CompatibilityError:
            incompatible character encodings: UTF-16LE and US-ASCII
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:557:in `include?'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:557:in `filter_object!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:562:in `block in filter_object!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:562:in `each'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:562:in `filter_object!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:562:in `block in filter_object!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:562:in `filter_object!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/structs.rb:550:in `filter!'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/configuration.rb:222:in `block in define_cassette_placeholder'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/util/hooks.rb:14:in `conditionally_invoke'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/util/hooks.rb:29:in `block in invoke_hook'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/util/hooks.rb:28:in `map'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/util/hooks.rb:28:in `invoke_hook'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:272:in `block (2 levels) in invoke_hook'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:271:in `tap'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:271:in `block in invoke_hook'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:270:in `delete_if'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:270:in `invoke_hook'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:257:in `block in interactions_to_record'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `tap'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:256:in `interactions_to_record'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:118:in `serializable_hash'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:263:in `write_recorded_interactions_to_disk'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:65:in `eject'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr.rb:156:in `eject_cassette'
          # /home/ixti/.gem/ruby/2.3.1/gems/vcr-3.0.3/lib/vcr/test_frameworks/rspec.rb:45:in `block (2 levels) in configure!'
          # /home/ixti/.gem/ruby/2.3.1/gems/sidekiq-4.1.4/lib/sidekiq/testing.rb:16:in `__set_test_mode'
          # /home/ixti/.gem/ruby/2.3.1/gems/sidekiq-4.1.4/lib/sidekiq/testing.rb:30:in `fake!'
```

gems involved in this:
- `vcr (3.0.3)`
- `webmock (2.1.0)`
- `google-api-client (0.9.15)`
  - `hurley (0.2)`
  - `httpclient (2.8.2.4)`

**Comment by ixti** [comment]
It might have been problem with `httpclient` or `webmock` as i don't have this issue anymore!
