### ISSUE TITLE
Webmock failing badly on Ruby 2.4.1

### ISSUE THREAD

**Issue by Jiri-Kremser** [vcr/vcr#647]
When trying to run our specs on ruby 2.4.1, all tests were red because of this error:

```bash
     NoMethodError:
       undefined method `close' for #<StubSocket:0x00000003d40eb0>
       Did you mean?  closed?
                      clone
     # /home/jkremser/.rvm/gems/ruby-2.4.1@test/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:125:in `start_without_connect'
     # /home/jkremser/.rvm/gems/ruby-2.4.1@test/gems/webmock-1.24.6/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
```

Do you plan to support 2.4.1?

Edit: mea culpa, updating the webmock to 3.x.x helped. Feel free to close this issue.

**Comment by bxt** [comment]
Yes, this is the same issue like in bblimke/webmock#683
