### ISSUE TITLE
VCR Does not Record SocketTimeouts

### ISSUE THREAD

**Issue by shalecraig** [vcr/vcr#650]
I tried to use VCR (with excon, if that matters) to record various types of errors so I can make sure a client library handles them correctly.

In the code before serialization, it doesn't seem like socket timeouts are considered.

Here's a code snippet that fails:

```ruby
puts VCR.version
# => 3.0.3
VCR.use_cassette('attempt_1', serialize_with: :json) do
  begin
    Excon.get('https://google.com', read_timeout: 0) # timeout on purpose
  rescue => e
    # log something here
  end
end
```

The JSON failure is on [this line](https://github.com/vcr/vcr/blob/master/lib/vcr/structs.rb#L494-L498), response is `nil`, and thererefore VCR fails with the following truncated snippet:
```
NoMethodError: undefined method `to_hash' for nil:NilClass
[....]/lib/vcr/structs.rb:497:in `to_hash'
```

**Comment by masterkain** [comment]
any solution to this? I have a long cassette with occasional timeouts and it's getting hard since it does not record anything before the exception that we trap

```
     2.2) Failure/Error: 'response'    => response.to_hash,

          NoMethodError:
            undefined method `to_hash' for nil:NilClass
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/structs.rb:497:in `to_hash'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:264:in `block in interactions_to_record'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:264:in `map'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:264:in `interactions_to_record'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:121:in `serializable_hash'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:271:in `write_recorded_interactions_to_disk'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/cassette.rb:68:in `eject'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr.rb:155:in `eject_cassette'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/vcr-4.0.0/lib/vcr/test_frameworks/rspec.rb:45:in `block (2 levels) in configure!'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-commands-rspec-1.0.4/lib/spring/commands/rspec.rb:18:in `call'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
          # /Users/kain/.rvm/gems/ruby-2.4.2/gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'




```

**Comment by krainboltgreene** [comment]
That's because a socket timeout isn't an HTTP request. It's pre-request.
