### ISSUE TITLE
When using allow_unused_http_interactions=false VCR crashes while handling a request not in the cassette

### ISSUE THREAD

**Issue by alanwushopify** [vcr/vcr#659]
Normally, if vcr gets a request not in the current cassette, it gives a nice error message. Something like:
```
  VCR::Errors::UnhandledHTTPRequestError:

  ================================================================================
  An HTTP request has been made that VCR does not know how to handle:
    GET http://www.iana.org/some_location_not_in_the_cassette

  VCR is currently using the following cassette:
...
```
But if `allow_unused_http_interactions` is turned off, like `VCR.use_cassette("synopsis", allow_unused_http_interactions: false)`, VCR crashes with `VCR::Errors::UnusedHTTPInteractionError`

Here is the log from a crash I was able to produce making minimal modification to the example in the README:

```
alanwu ~/t/vcr [1]> bundle exec ruby test.rb
Loaded suite test
Started
E
==================================================================================================================================================================================================================================
Error: test_example_dot_com(VCRTest):
  VCR::Errors::UnusedHTTPInteractionError: There are unused HTTP interactions left in the cassette:
    - [get http://www.iana.org/domains/reserved] => [200 "<!doctype html>\n<html>\n<head>\n\t<title>IANA \xE2\x80\x94 IANA-managed Reserved Domains</ti"]
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/cassette/http_interaction_list.rb:68:in `assert_no_unused_interactions!'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/cassette.rb:68:in `eject'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr.rb:156:in `eject_cassette'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:96:in `block in current_cassettes'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:95:in `loop'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:95:in `current_cassettes'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:122:in `current_matchers'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:118:in `match_request_on_body?'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:110:in `request_description'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:84:in `construct_message'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/errors.rb:72:in `initialize'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/request_handler.rb:97:in `new'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/request_handler.rb:97:in `on_unhandled_request'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/library_hooks/webmock.rb:129:in `on_unhandled_request'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/request_handler.rb:24:in `handle'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/library_hooks/webmock.rb:144:in `block in <module:WebMock>'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:28:in `block in register_global_stub'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/request_pattern.rb:36:in `matches?'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `each'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `detect'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/stub_registry.rb:50:in `response_for_request'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
/opt/rubies/2.4.1/lib/ruby/2.4.0/net/http.rb:1317:in `request_get'
/opt/rubies/2.4.1/lib/ruby/2.4.0/net/http.rb:487:in `block in get_response'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/http_lib_adapters/net_http.rb:123:in `start_without_connect'
/Users/alanwu/.gem/ruby/2.4.1/gems/webmock-3.0.1/lib/webmock/http_lib_adapters/net_http.rb:150:in `start'
/opt/rubies/2.4.1/lib/ruby/2.4.0/net/http.rb:608:in `start'
/opt/rubies/2.4.1/lib/ruby/2.4.0/net/http.rb:485:in `get_response'
test.rb:13:in `block in test_example_dot_com'
     10: class VCRTest < Test::Unit::TestCase
     11:   def test_example_dot_com
     12:     VCR.use_cassette("synopsis", allow_unused_http_interactions: false) do
  => 13:       response = Net::HTTP.get_response(URI('http://www.iana.org/some_location_not_in_the_cassette'))
     14:       assert_match /Example domains/, response.body
     15:     end
     16:   end
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
/Users/alanwu/.gem/ruby/2.4.1/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
test.rb:12:in `test_example_dot_com'
==================================================================================================================================================================================================================================


Finished in 0.008661 seconds.
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 0 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
115.46 tests/s, 0.00 assertions/s
```

I made a repo with the exact code + cassette I used: https://github.com/alanwushopify/VCR-bug-report

Remove `allow_unused_http_interactions: false` and the nice error message shows up.

**Comment by ikapelyukhin** [comment]
@alanwushopify So you have an unused interaction in with the cassette (a request to `http://www.iana.org/domains/reserved`), you have set to `allow_unused_http_interactions` to `false`, and now you are getting `VCR::Errors::UnusedHTTPInteractionError` (because... You have disallowed unused interactions).

What seems to be the problem?

Seems like `UnhandledHTTPRequestError` doesn't get a chance to fire because `UnusedHTTPInteractionError` fires first.

**Comment by alanwushopify** [comment]
The problem is that VCR ends up raising `UnusedHTTPInteractionError` while trying to construct a `UnhandledHTTPRequestError`. I don't think this is correct behaviour because usually `UnusedHTTPInteractionError` gets raised after the block I give to `#use_cassette` finishes running. As is, `UnusedHTTPInteractionError` is raised when VCR encounters the first unknown request.

Any code after the first unknown request don't get to execute.

If I give a bock to `#use_cassette` that consumes all the request in the cassette and does an unknown request at the beginning, I get an `UnusedHTTPInteractionError`. I don't think this makes sense.
