### ISSUE TITLE
VCR throws error, when :record is set to :none after recording new cassette from :new_episodes

### ISSUE THREAD

**Issue by rubhanazeem** [vcr/vcr#718]
I've recorded a new cassette with `:record => :new_episodes` now when I set `:record => :none` vcr throws this error 

```
VCR::Errors::UnhandledHTTPRequestError:
     
     
       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET https://www.googleapis.com/calendar/v3/calendars/primary/events?fields=items(end,%20id,%20start),%20nextPageToken&maxResults=1000&showDeleted=false&timeMin=2018-08-23T04:19:16%2B05:00
     
       VCR is currently using the following cassette:
         - /Users/OsmanAzeem/sites/jadie/spec/fixtures/vcr/ApiController/meetings/should_return_users_future_events_from_GetFutureEventsForChrome.yml
           - :record => :none
           - :match_requests_on => [:method, :uri]
```

vcr.rb
```
VCR.configure do |c|
  c.ignore_localhost = true
  c.cassette_library_dir = File.join(File.dirname(__FILE__), '../fixtures/vcr')
  c.hook_into :webmock
  c.configure_rspec_metadata!
  c.allow_http_connections_when_no_cassette = false

  c.default_cassette_options = { :record => :none }
end

```

test
```
it "should return users future events from GetFutureEventsForChrome", vcr: true do
...
end
```

**Comment by coding-bunny** [comment]
I'm running into similar problems, however by trying to enable the `filter_sensitive_data` option in our configuration.

We have recorded 7 cassettes, but they all include the Basic Auth token in the headers. So I wanted to tweak the configuration as follows, to substitute this:

```
VCR.configure do |vcr_config|
  vcr_config.cassette_library_dir = "#{RSPEC_ROOT}/fixtures/vcr_cassettes"
  vcr_config.hook_into :webmock
  vcr_config.configure_rspec_metadata!
  vcr_config.allow_http_connections_when_no_cassette = false
  vcr_config.default_cassette_options = {
    match_requests_on: [:uri, :method, :body, :headers],
    record: :none
  }

  # Adding this line to filter out our Auth Token
  vcr_config.filter_sensitive_data("<RBE_AUTH_TOKEN>") { ::Builder::System.tokens["bulk_order_api"] }
end
```

And I manually edited the cassettes, to replace the Auth Token with `<RBE_AUTH_TOKEN>`, so that the cassettes would still be picked up by VCR when the recording is disabled, however I'm receiving for all these cassettes the Unauthorized HTTP Request error.

I've enabled the debug output for these cassettes to determine what's going wrong and why VCR fails to match them. This is the complete output from one test where the modifications are made:

```
[Cassette: 'Integration_Tests/contains_the_required_stategy_in_the_payload'] Initialized with options: {:record=>:none, :match_requests_on=>[:uri, :method, :body, :headers], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system}
  [Cassette: 'Integration_Tests/contains_the_required_stategy_in_the_payload'] Initialized HTTPInteractionList with request matchers [:uri, :method, :body, :headers] and 0 interaction(s): {  }
[Cassette: 'Builder::Autoart/Integration Tests/contains the required stategy in the payload'] Initialized with options: {:record=>:none, :match_requests_on=>[:uri, :method, :body, :headers], :allow_unused_http_interactions=>true, :serialize_with=>:yaml, :persist_with=>:file_system}
2019-05-27 13:41:03 +0200 : Downloading https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json - attempt 0
[webmock] Handling request: [get http://169.254.169.254/latest/meta-data/instance-id "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"]}] (disabled: false)
[VCR::Configuration] before_playback: replacing "<RBE_AUTH_TOKEN>" with "872edb5be254ba0d8af1a70b22aa25ab"
  [Cassette: 'Builder::Autoart/Integration Tests/contains the required stategy in the payload'] Initialized HTTPInteractionList with request matchers [:uri, :method, :body, :headers] and 1 interaction(s): { [get https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"], "Rockwell-Builder-Ip"=>["192.168.9.185"], "Rockwell-Builder-Platform"=>["lin"], "Authorization"=>["Token token=872edb5be254ba0d8af1a70b22aa25ab"]}] => [200 "{\"front\":{\"art_constraint\":{\"area_name\":\"Left/Right Chest\",\"width\":5.0,\"height\":"] }
  [Cassette: 'Builder::Autoart/Integration Tests/contains the required stategy in the payload'] Checking if [get http://169.254.169.254/latest/meta-data/instance-id "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"]}] matches [get https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"], "Rockwell-Builder-Ip"=>["192.168.9.185"], "Rockwell-Builder-Platform"=>["lin"], "Authorization"=>["Token token=872edb5be254ba0d8af1a70b22aa25ab"]}] using [:uri, :method, :body, :headers]
    [Cassette: 'Builder::Autoart/Integration Tests/contains the required stategy in the payload'] uri (did not match): current request [get http://169.254.169.254/latest/meta-data/instance-id "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"]}] vs [get https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"], "Rockwell-Builder-Ip"=>["192.168.9.185"], "Rockwell-Builder-Platform"=>["lin"], "Authorization"=>["Token token=872edb5be254ba0d8af1a70b22aa25ab"]}]
[webmock] Identified request type (unhandled) for [get http://169.254.169.254/latest/meta-data/instance-id "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"]}]
[webmock] Handling request: [get https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"], "Rockwell-Builder-Ip"=>["192.168.9.185"], "Rockwell-Builder-Platform"=>["lin"], "Authorization"=>["Token token=872edb5be254ba0d8af1a70b22aa25ab"]}] (disabled: false)
[webmock] Identified request type (unhandled) for [get https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json "" {"Accept-Encoding"=>["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"], "Accept"=>["*/*"], "User-Agent"=>["Ruby"], "Rockwell-Builder-Ip"=>["192.168.9.185"], "Rockwell-Builder-Platform"=>["lin"], "Authorization"=>["Token token=872edb5be254ba0d8af1a70b22aa25ab"]}]

VCR::Errors::UnhandledHTTPRequestError: 

================================================================================
An HTTP request has been made that VCR does not know how to handle:
  GET https://be-master.staging.customink.com/backend/api/v2/orders/30737062/autoart.json
  Headers:
    Accept-Encoding: "gzip;q=1.0,deflate;q=0.6,identity;q=0.3"
    Accept: "*/*"
    User-Agent: "Ruby"
    Rockwell-Builder-Ip: "192.168.9.185"
    Rockwell-Builder-Platform: "lin"
    Authorization: "Token token=872edb5be254ba0d8af1a70b22aa25ab"
  Body: 

There is currently no cassette in use. There are a few ways
you can configure VCR to handle this request:

  * If you're surprised VCR is raising this error
    and want insight about how VCR attempted to handle the request,
    you can use the debug_logger configuration option to log more details [1].
  * If you want VCR to record this request and play it back during future test
    runs, you should wrap your test (or this portion of your test) in a
    `VCR.use_cassette` block [2].
  * If you only want VCR to handle requests made while a cassette is in use,
    configure `allow_http_connections_when_no_cassette = true`. VCR will
    ignore this request since it is made when there is no cassette [3].
  * If you want VCR to ignore this request (and others like it), you can
    set an `ignore_request` callback [4].

[1] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/debug-logging
[2] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/getting-started
[3] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/allow-http-connections-when-no-cassette
[4] https://www.relishapp.com/vcr/vcr/v/4-0-0/docs/configuration/ignore-request
================================================================================


/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/request_handler.rb:97:in `on_unhandled_request'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/library_hooks/webmock.rb:129:in `on_unhandled_request'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/request_handler.rb:24:in `handle'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/library_hooks/webmock.rb:144:in `block in <module:WebMock>'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:28:in `call'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:28:in `block in register_global_stub'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/request_pattern.rb:36:in `call'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/request_pattern.rb:36:in `matches?'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:58:in `block in request_stub_for'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:57:in `each'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:57:in `detect'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:57:in `request_stub_for'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/stub_registry.rb:50:in `response_for_request'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/webmock-1.24.2/lib/webmock/http_lib_adapters/net_http.rb:79:in `request'
./lib/builder/downloader.rb:73:in `block in get_response'
./lib/builder/downloader.rb:58:in `times'
./lib/builder/downloader.rb:58:in `get_response'
./lib/builder/autoart.rb:43:in `autoart_data'
./spec/lib/builder/autoart_spec.rb:71:in `block (3 levels) in <top (required)>'
./spec/lib/builder/autoart_spec.rb:96:in `block (3 levels) in <top (required)>'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
/home/olivar/.rvm/gems/ruby-2.1.6/gems/vcr-4.0.0/lib/vcr.rb:188:in `use_cassette'
./spec/spec_helper.rb:59:in `block (2 levels) in <top (required)>'
```

And what strikes me as odd, is that the URI matchers suddenly fail when this is enabled. E.g it's comparing the URL of the request against the actual IP for these tests, something it didn't do before.
When I remove the `filter_sensitive_data` and restore the cassette however it all works.
I can delete the cassette, and regenerate them with the filtering, which makes them pass on the first run, but as soon as the recording is disabled the errors appear again.

**Comment by coding-bunny** [comment]
Running into this problem again with a different project now.
Bumped VCR and Webmock to the latest versions, deleted all cassettes, and then ran a suite with `record: :all`, everything works. As soon as I swap to `:none` or `:once`, I have specs failing all over the place because VCR cannot find a matching request, and has "unplayed recordings"

**Comment by nicolasiensen** [comment]
In the error message reported by @rubhanazeem, the request that raised the exception contains the following query param:

```
timeMin=2018-08-23T04:19:16%2B05:00
```

I wonder if the value of `timeMin` is precisely the same between each test run. If not, VCR won't match the following request with the recorded cassette because the URIs differ.

If this is the case, I would recommend changing the test, so the parameter is always the same between each test run. Another option would be to ignore the `timeMin` query param using [VCR::RequestMatcherRegistry#uri_without_params](https://www.rubydoc.info/github/vcr/vcr/VCR%2FRequestMatcherRegistry:uri_without_params).

@coding-bunny, could you please check if your problem has the same root cause? If not, could you please try to reproduce this problem with an isolated example and post it here?

**Comment by coding-bunny** [comment]
It's not a timing issue sadly. I'm currently running into this problem again with a different set of tests.
Every time I run the test-suite again, VCR insists on recording the cassette again, instead of the re-using the one it has in place. The only difference between these cassettes is the values of the headers, despite the matching for cassettes to be set to `match_requests_on: %i[method uri body]`

Here are some of the diffs:

```
headers:
      Date:
-      - Mon, 22 Jun 2020 11:46:26 GMT
+      - Mon, 22 Jun 2020 12:00:00 GMT

```

```
X-Request-Id:
-      - 0bd706a1-ab0e-4ec7-8771-eb38b58daa08
+      - 8b37e72b-0fd8-4a99-8067-f7bf5b9e6b89
```

It' always the following headers that change:

* Transfer-Encoding
* Content-Length
* X-Runtime
* X-Request-Id
* Date
* E-Tag

And only the responses, never the requests. So for whatever reason VCR does not consider the outgoing request the same
as what is recorded even though the diff shows now changes. As soon as I commit the changes, and run the same spec again, the cassette will have been overwritten again by VCR with the exact same headers changed.

Here is a snippet from the debug log :

```
[Cassette: 'FulfillmentTrackPipeline/#submit/when already in the CustomInk system multiple times/puts the track into error status'] Recorded HTTP interaction [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"] => [200 "[{\"id\":232075,\"reference_id\":\"o_111#ft_111\",\"fix_of\":null,\"reference_name\":\"test"]
  Initialized HTTPInteractionList with request matchers [:method, :uri, :body] and 4 interaction(s): { [get https://master.staging.customink.com/api/designs/rss0-00c6-4vsa?api_version=5 ""] => [200 "{\"personalization\":[],\"designId\":476915317,\"designName\":\"test\",\"designIdeaId\":nu"], [get http://mms.in.customink.com/mms/api/styles/6100.json ""] => [200 "{\"_id\":6100,\"__id_leading_zero\":true,\"__singles_alternative_id_leading_zero\":tru"], [get http://mms.in.customink.com/mms/api/v1/skus.json?style_id=6100 ""] => [200 "[{\"id\":301149,\"style_id\":6100,\"color_id\":6100,\"size_id\":\"L\",\"status\":\"active\"},{"], [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"] => [200 "[{\"id\":232075,\"reference_id\":\"o_111#ft_111\",\"fix_of\":null,\"reference_name\":\"test"] }
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get https://master.staging.customink.com/api/designs/rss0-00c6-4vsa?api_version=5 ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get https://master.staging.customink.com/api/designs/rss0-00c6-4vsa?api_version=5 ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://mms.in.customink.com/mms/api/styles/6100.json ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://mms.in.customink.com/mms/api/styles/6100.json ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://mms.in.customink.com/mms/api/v1/skus.json?style_id=6100 ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://mms.in.customink.com/mms/api/v1/skus.json?style_id=6100 ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"]
```

This is where the matching goes wrong, because from what I understand the interactions don't make sense anymore.
And I noticed this mismatch started when we upgraded VCR.
It seems from our point of view that V6 has issues with cassettes recorded under V5

**Comment by coding-bunny** [comment]
```
Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get https://master.staging.customink.com/api/designs/rss0-00c6-4vsa?api_version=5 ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get https://master.staging.customink.com/api/designs/rss0-00c6-4vsa?api_version=5 ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://mms.in.customink.com/mms/api/styles/6100.json ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://mms.in.customink.com/mms/api/styles/6100.json ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://mms.in.customink.com/mms/api/v1/skus.json?style_id=6100 ""] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://mms.in.customink.com/mms/api/v1/skus.json?style_id=6100 ""]
  Checking if [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] matches [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"] using [:method, :uri, :body]
    method (did not match): current request [post http://order-fulfillment-service-master.staging.customink.com/fulfillments "{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"] vs [get http://order-fulfillment-service-master.staging.customink.com/fulfillments?reference_ids=o_111%23ft_111 "{}"]
```

This specific calls is not being matched for whatever reason by VCR.

**Comment by nicolasiensen** [comment]
Could you try to reproduce this issue on a separate file and post it here? You can try something like this:

```ruby
require 'vcr'
require 'net/http'

VCR.configure do |config|
  config.cassette_library_dir = "cassettes"
  config.hook_into :webmock
end

VCR.use_cassette('example') do
  Net::HTTP.get_response(URI('http://www.google.com/'))
end
```

On a side note, I noticed from the logs you posted that what I think is the body of your request seems that to have an invalid JSON payload:

```
"{\"fulfillment\":{\"reference_id\":\"o_111#ft_111\",\"reference_name\":\"test\",\"reference"
```

I don't think VCR would care if the body has a valid payload or not, but perhaps it is something you could investigate on your end.

**Comment by bendillinger** [comment]
Was running into this on only one of our HTTP clients that extends from https://github.com/httprb/http
For some reason `VCR` would always perform a real request, even when identical -- same as coding-bunny a few comments above where only the response headers are changing.

Turns out, adding `.headers("Content-Type" => "application/json")` allowed `VCR` to recognize it as the same request and not perform another real one.
I didn't look very hard into why but if someone else is struggling maybe this could help.
