### ISSUE TITLE
Fix test failures with excon 0.72

### ISSUE THREAD

**Issue by pravi** [vcr/vcr#801]
We'd like to update ruby-excon to 0.72 in debian but 4 tests are failing with error messages like this

```
  1) Excon hook behaves like a hook into an HTTP library using Excon .stub_requests using specific match_attributes :headers returns the expected response for a {"X-Http-Header1"=>"val1"} request
     Failure/Error: raise VCR::Errors::UnhandledHTTPRequestError.new(vcr_request)
     
     VCR::Errors::UnhandledHTTPRequestError:
     
     
       ================================================================================
       An HTTP request has been made that VCR does not know how to handle:
         GET http://wrong-domain.com/wrong/path
     
       There is currently no cassette in use. There are a few ways
       you can configure VCR to handle this request:
     
         * If you're surprised VCR is raising this error
           and want insight about how VCR attempted to handle the request,
           you can use the debug_logger configuration option to log more details [1].
         * If you want VCR to record this request and play it back during future test
           runs, you should wrap your test (or this portion of your test) in a
           `VCR.use_cassette` block [2].
         * If you only want VCR to handle requests made while a cassette is in use,
           configure `allow_http_connections_when_no_cassette = true`. VCR will
           ignore this request since it is made when there is no cassette [3].
         * If you want VCR to ignore this request (and others like it), you can
           set an `ignore_request` callback [4].
     
       [1] https://www.relishapp.com/vcr/vcr/v/5-1-0/docs/configuration/debug-logging
       [2] https://www.relishapp.com/vcr/vcr/v/5-1-0/docs/getting-started
       [3] https://www.relishapp.com/vcr/vcr/v/5-1-0/docs/configuration/allow-http-connections-when-no-cassette
       [4] https://www.relishapp.com/vcr/vcr/v/5-1-0/docs/configuration/ignore-request
       ================================================================================
     Shared Example Group: "a hook into an HTTP library" called from ./spec/lib/vcr/library_hooks/excon_spec.rb:15
     # ./lib/vcr/request_handler.rb:97:in `on_unhandled_request'
     # ./lib/vcr/request_handler.rb:24:in `handle'
     # ./lib/vcr/middleware/excon.rb:68:in `before_request'
     # ./lib/vcr/middleware/excon.rb:20:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/mock.rb:57:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/instrumentor.rb:34:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/idempotent.rb:19:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/middlewares/base.rb:22:in `request_call'
     # ./vendor/bundle/ruby/2.5.0/gems/excon-0.72.0/lib/excon/connection.rb:275:in `request'
     # ./spec/support/http_library_adapters.rb:226:in `make_http_request'
     # ./spec/support/shared_example_groups/hook_into_http_library.rb:471:in `make_http_request'
     # ./spec/support/shared_example_groups/hook_into_http_library.rb:429:in `block (3 levels) in matching_on'
```

Updated excon version to 0.72.0 in gemspec and ran bundle install, bundle exec rake

Ruby 2.5
Gem 5.1.0
HTTP same as the version that passed
Mock same as the version that passed
Rails {{Replace with version if applicable}}
Rspec {{Replace with version if applicable}}

**Comment by utkarsh2102** [comment]
Could reproduce this:

```
Failed examples:

rspec './spec/lib/vcr/library_hooks/excon_spec.rb[1:1:1:11:6:1]' # Excon hook behaves like a hook into an HTTP library using Excon .stub_requests using specific match_attributes :headers returns the expected response for a {"X-Http-Header1"=>"val1"} request
rspec './spec/lib/vcr/library_hooks/excon_spec.rb[1:1:1:11:6:2]' # Excon hook behaves like a hook into an HTTP library using Excon .stub_requests using specific match_attributes :headers returns the expected response for a {"X-Http-Header1"=>"val2"} request
rspec './spec/lib/vcr/library_hooks/webmock_spec.rb[1:12:1:11:6:1]' # WebMock hook behaves like a hook into an HTTP library using Excon .stub_requests using specific match_attributes :headers returns the expected response for a {"X-Http-Header1"=>"val1"} request
rspec './spec/lib/vcr/library_hooks/webmock_spec.rb[1:12:1:11:6:2]' # WebMock hook behaves like a hook into an HTTP library using Excon .stub_requests using specific match_attributes :headers returns the expected response for a {"X-Http-Header1"=>"val2"} request
```

Could someone possibly take a look at this?
CC: @ryanb @olleolleolle @ericallam @mislav

**Comment by olleolleolle** [comment]
Can you figure out which versions do work? 

0.62.0 is the current pin. There are many versions in between. 

It would help the fix to know where the chain hopped of the bicycle.

**Comment by pravi** [comment]
There is a deprecation warning with 0.62,

`/home/pravi/forge/vcr/vendor/bundle/ruby/2.7.0/gems/excon-0.62.0/lib/excon.rb:170: warning: Capturing the given block using Proc.new is deprecated; use `&block` instead`

**Comment by olleolleolle** [comment]
(The deprecation warning is fixed in excon `master`.)

**Comment by dleidert** [comment]
I've debugged the issue for Debian further and changed the log() entry in `interaction_matches_request?` (`lib/vcr/cassette/http_interaction_list.rb`) a bit to inspect the headers. With the different excon versions there are different headers.

with excon 0.60 the request headers match:
```
headers (matched): current request {"User-Agent"=>["excon/0.60.0"], "X-Http-Header1"=>["val1"]} vs {"X-Http-Header1"=>["val1"], "User-Agent"=>["excon/0.60.0"]}
          returns the expected response for a {"X-Http-Header1"=>"val1"} request
```

with excon 0.72 interaction_matches_request?() produces a failure:
```
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"X-Http-Header1"=>["val1"], "User-Agent"=>["excon/0.72.0"]}
headers (did not match): current request {"User-Agent"=>["excon/0.72.0"], "Accept"=>["*/*"], "X-Http-Header1"=>["val1"]} vs {"X-Http-Header1"=>["val2"], "User-Agent"=>["excon/0.72.0"]}
          returns the expected response for a {"X-Http-Header1"=>"val1"} request (FAILED - 1)
```

Is it possible that the new `Accept` header fails the test?
<https://github.com/excon/excon/compare/v0.60.0...v0.72.0#diff-923a15667514d380032eaccc863a7c50L120>

**Comment by dleidert** [comment]
Possible patch:

```
--- a/spec/support/http_library_adapters.rb	2020-03-30 14:01:06.000000000 +0200
+++ b/spec/support/http_library_adapters.rb	2020-03-30 15:14:21.791852803 +0200
@@ -227,7 +227,7 @@ HTTP_LIBRARY_ADAPTERS['excon'] = Module.
   end
 
   def normalize_request_headers(headers)
-    headers.merge('User-Agent' => [Excon::USER_AGENT])
+    headers.merge('User-Agent' => [Excon::USER_AGENT], 'Accept' => ['*/*'])
   end
 end
```

**Comment by krainboltgreene** [comment]
@dleidert Feel free to open a PR!

**Comment by dleidert** [comment]
Done
