### ISSUE TITLE
Crashing with minitest >= 5.16.0

### ISSUE THREAD

**Issue by morgoth** [vcr/vcr#944]
There were big changes in minitest 5.16.0 in regards to kwargs arguments https://github.com/minitest/minitest/blob/master/History.rdoc#5160--2022-06-14-

Using this minitest version is crashing VCR with error:
```
/home/wojtek/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/vcr-6.1.0/lib/vcr/errors.rb:97:in `method': wrong number of arguments (given 0, expected 1) (ArgumentError)
```

This happens when some already recorded cassette is stale (some params changed) and the info is reported: `An HTTP request has been made that VCR does not know how to handle...`

My VCR config:
```ruby
VCR.configure do |c|
  c.default_cassette_options = {record: :once}
  c.cassette_library_dir = Rails.root.join('test', 'vcr', 'cassettes')
  c.hook_into :webmock
  c.ignore_localhost = true
end
```

Ruby ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [x86_64-linux
VCR Gem 6.1.0
Rails 7.0.3

**Comment by bkeepers** [comment]
I'm getting this too with minitest 5.16.2

**Comment by ytjmt** [comment]
It seems to be fixed with minitest `5.16.3`.
https://github.com/minitest/minitest/compare/v5.16.2...v5.16.3

- `test_foo.rb`

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'

  gem 'minitest', '5.16.2' # '5.16.3'
  gem 'vcr', '6.1.0'
  gem 'webmock', '3.18.1'
end

require 'minitest/autorun'
require 'vcr'
require 'net/http'

VCR.configure do |config|
  config.cassette_library_dir = 'fixtures'
  config.hook_into :webmock
end

class TestFoo < Minitest::Test
  def test_foo
    VCR.use_cassette('cassette') do
      response = Net::HTTP.get_response(URI('https://www.example.com/foo/bar'))
      assert_equal 'foo', response.body
    end
  end
end
```

- `fixtures/cassette.yml`

```yml
---
http_interactions:
- request:
    method: get
    uri: https://www.example.com/
  response:
    status:
      code: 200
      message: OK
  recorded_at: Wed, 05 Oct 2022 14:01:38 GMT
recorded_with: VCR 6.1.0
```

- `minitest 5.16.2`

```
$ ruby test_foo.rb 
Run options: --seed 37835

# Running:

/Users/tsujimoto/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/vcr-6.1.0/lib/vcr/errors.rb:97:in `method': wrong number of arguments (given 0, expected 1) (ArgumentError)
...
```

- `minitest 5.16.3`

```
$ ruby test_foo.rb 
Run options: --seed 28731

# Running:

E

Finished in 0.006609s, 151.3088 runs/s, 0.0000 assertions/s.

  1) Error:
TestFoo#test_foo:
RuntimeError: Neutered Exception VCR::Errors::UnhandledHTTPRequestError: 

================================================================================
An HTTP request has been made that VCR does not know how to handle:
  GET https://www.example.com/foo/bar
...
```

**Comment by olleolleolle** [comment]
@ytjmt Thanks for taking the time to clear that up!

This improves the searchability of this Issue.

@morgoth Does this work out your issue?

**Comment by morgoth** [comment]
Yes, looks like now it's working correct.
Thank you.
