### ISSUE TITLE
cucumber test fails on additional webmock curb output

### ISSUE THREAD

**Issue by olleolleolle** [vcr/vcr#948]
The test suite reports an error - in the cucumber tests, which look a bit like this:

> +You are using Curb 0.9.11. WebMock is known to work with Curb >= 0.7.16, < 1.1, except versions 0.8.7. It may not work with this version.

I saw this in CI, and I am repeating the content here, so as not to lose it when the logs grow old.

<details>

```
expected "Valid encoding: false\n\nRecording:\nBody: \"abc \\xFA\"\n\nPlayback:\nBody: \"abc \\xFA\"\nYou are ...known to work with Curb >= 0.7.16, < 1.1, except versions 0.8.7. It may not work with this version." to output string is eq: "Valid encoding: false\n\nRecording:\nBody: \"abc \\xFA\"\n\nPlayback:\nBody: \"abc \\xFA\"\n"
Diff:
@@ -5,4 +5,5 @@
 
 Playback:
 Body: "abc \xFA"
+You are using Curb 0.9.11. WebMock is known to work with Curb >= 0.7.16, < 1.1, except versions 0.8.7. It may not work with this version.
 (RSpec::Expectations::ExpectationNotMetError)
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.1/lib/rspec/support.rb:102:in `block in <module:Support>'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.11.1/lib/rspec/support.rb:111:in `notify_failure'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/fail_with.rb:35:in `fail_with'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/handler.rb:38:in `handle_failure'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/handler.rb:56:in `block in handle_matcher'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/handler.rb:27:in `with_matcher'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/handler.rb:48:in `handle_matcher'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/expectation_target.rb:65:in `to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/rspec-expectations-3.11.1/lib/rspec/expectations/expectation_target.rb:101:in `to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/aruba-0.14.14/lib/aruba/cucumber/command.rb:206:in `block in <top (required)>'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/glue/invoke_in_world.rb:36:in `instance_exec'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/glue/invoke_in_world.rb:36:in `block in cucumber_instance_exec_in'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/glue/invoke_in_world.rb:50:in `cucumber_run_with_backtrace_filtering'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/glue/invoke_in_world.rb:26:in `cucumber_instance_exec_in'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/glue/step_definition.rb:133:in `invoke'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/step_match.rb:33:in `invoke'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/step_match.rb:26:in `block in activate'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/action.rb:23:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/step.rb:35:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:106:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:53:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:29:in `test_step'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/step.rb:23:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:31:in `block (3 levels) in describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:30:in `each'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:30:in `block (2 levels) in describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/prepare_world.rb:23:in `block in test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/around_hook.rb:21:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:106:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:53:in `execute'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:36:in `around_hook'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/around_hook.rb:12:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:80:in `block (2 levels) in compose_around_hooks'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:81:in `compose_around_hooks'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:29:in `block in describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/runner.rb:19:in `test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/prepare_world.rb:11:in `test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:57:in `test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/retry.rb:18:in `test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/quit.rb:11:in `test_case'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/case.rb:28:in `describe_to'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:21:in `block in done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `map'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/filters/broadcast_test_run_started_event.rb:20:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/filters/locations_filter.rb:20:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/filter.rb:62:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/test/filters/tag_filter.rb:18:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/compiler.rb:31:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core/gherkin/parser.rb:46:in `done'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core.rb:35:in `parse'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-core-10.1.1/lib/cucumber/core.rb:24:in `compile'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/runtime.rb:83:in `run!'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/lib/cucumber/cli/main.rb:29:in `execute!'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/gems/cucumber-7.1.0/bin/cucumber:9:in `<top (required)>'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/bin/cucumber:23:in `load'
/home/runner/work/vcr/vcr/vendor/bundle/ruby/2.7.0/bin/cucumber:23:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:58:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:58:in `kernel_load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli/exec.rb:23:in `run'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:486:in `exec'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:31:in `dispatch'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/cli.rb:25:in `start'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/exe/bundle:48:in `block in <top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/lib/bundler/friendly_errors.rb:120:in `with_friendly_errors'
/opt/hostedtoolcache/Ruby/2.7.6/x64/lib/ruby/gems/2.7.0/gems/bundler-2.3.23/exe/bundle:36:in `<top (required)>'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `load'
/opt/hostedtoolcache/Ruby/2.7.6/x64/bin/bundle:23:in `<main>'
features/configuration/preserve_exact_body_bytes.feature:55:in `the output should contain exactly:'

Failing Scenarios:
cucumber features/configuration/preserve_exact_body_bytes.feature:20 # Scenario: Preserve exact bytes for response body with invalid encoding
```

</details>

**Comment by olleolleolle** [comment]
I marked this bug, but it is an incompatibility in our testing stack.

Needs poking around

**Comment by ryanseys** [comment]
Fix in https://github.com/vcr/vcr/pull/949

**Comment by olleolleolle** [comment]
@ryanseys This is indeed fixed!
