### ISSUE TITLE
Memory corruption in HTTP interaction serialization on Ruby 3.2.0

### ISSUE THREAD

**Issue by kmewhort** [vcr/vcr#964]
Using:
- Ruby: 3.2.0 (error NOT present with 3.1.2 or earlier; still present on the latest 3.2.1)
- VCR: 6.1.0 (reproducable with earlier); using Webmock, YAML serializer
- OS: macOS Monterey, 12.1

As of upgrading to Ruby 3.2.0, when *recording* a cassette that gets back a long binary response, the serialization usually completely hangs, and I sometimes gives a malloc error. I can consintenly reproduce with the following trivial example:

```
require "rails_helper"
require "net/http"

RSpec.describe "MallocError", :vcr do
  it "records the cassette" do
    Net::HTTP.get(
      URI("https://uwaterloo.ca/onbase/sites/ca.onbase/files/uploads/files/sampleunsecuredpdf.pdf"),
    )
  end
end
```

The malloc error that comes up about 1 in 10 runs is:
```
ruby(25770,0x10532c580) malloc: *** error for object 0x6000095bf5f0: pointer being freed was not allocated
ruby(25770,0x10532c580) malloc: *** set a breakpoint in malloc_error_break to debug
```

The error occurs at the `::YAML.dump(hash)` in `lib/vcr/cassette/serializers/yaml.rb:37`.  You can reproduce by putting a breakpoint there and trying that line.

Interestingly, if at this point in the code, you try serializing just the string but not the full hash, there's a serialization error, but no hang:
```
str = hash['http_interactions'][0]['response']['body']['string']
::YAML.dump(str)

eval error: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS
  /Users/kent/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/psych/visitors/emitter.rb:32:in `scalar'
  /Users/kent/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/psych/visitors/emitter.rb:32:in `visit_Psych_Nodes_Scalar'
  /Users/kent/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/psych/visitors/visitor.rb:30:in `visit'
  /Users/kent/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/psych/visitors/visitor.rb:6:in `accept'
  /Users/kent/.rvm/rubies/ruby-3.2.0/lib/ruby/3.2.0/psych/visitors/emitter.rb:27:in `block in visit_Psych_Nodes_Document'
```

If you clobber the string (`hash['http_interactions'][0]['response']['body']['string'] = ""`) it'll pass completely.  So the issue arises only in a combination of the invalid, long response string with the rest of the request hash.

Going back to this invalid string...you can get the error with just one character:
```
YAML.dump(str[10])
eval error: expected SCALAR, SEQUENCE-START, MAPPING-START, or ALIAS
```

Which is this character:
```
(ruby) str[10]
"\xC7"
(ruby) str[10].dump
"\"\\xC7\""
```

So definitely not valid UTF-8, but this the error I would expect:
```
(ruby) ::YAML.dump("\xC7")
eval error: invalid byte sequence in UTF-8

(ruby) ::YAML.dump(str.dump.undump)
eval error: invalid byte sequence in UTF-8
```
Two different errors from what looks from the outside be the exact same character.  This means there's something funky about that String instantiation itself.  I thus suspect the memory in the string has actually been de-allocated or corrupted, especially given the malloc error that comes up sometimes.

I'm not sure if I should raise this issue to `ruby` itself, but I can only reproduce through VCR...if it's a ruby issue, anyone have insight on how VCR is acting on the String to get into this state (so we can distill it to a simpler repro for `ruby`)?

**Comment by olleolleolle** [comment]
💡 Perhaps you can raise this as a more-technical topic in [the Psych (YAML library for Ruby) Discussion Forum](https://github.com/ruby/psych/discussions)?

**Comment by olleolleolle** [comment]
> @olleolleolle, good idea. Done: [ruby/psych#619](https://github.com/ruby/psych/discussions/619)

(Ah, nice. I _think_ the title and first sentence should refer to 3.2.0, not 2.3.0.)

**Comment by kmewhort** [comment]
> > @olleolleolle, good idea. Done: [ruby/psych#619](https://github.com/ruby/psych/discussions/619)
> 
> (Ah, nice. I _think_ the title and first sentence should refer to 3.2.0, not 2.3.0.)

Whoops, nice catch, thanks!  My mind must've wandered back a decade there.

**Comment by bmulholland** [comment]
FWIW, seems to be affecting others using vcr, too: https://github.com/ruby/psych/discussions/619#discussioncomment-5266934
